name: XAUUSDexit

on:
  schedule:
    - cron: "10 15 * * 1-5"   # 4:10 PM Nigeria time
  workflow_dispatch:

jobs:
  run-exit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run XAUUSD exit bot
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
        run: python XAUUSDexit.py
